### ISSUE TITLE
'psc' already exists in pypi...

### ISSUE THREAD

**Issue by tildebyte** [pauleveritt/psc#34]
...to my consternation when trying `pipx psc` 😆

- '[psc](https://pypi.org/project/psc)' - a "parameter store client" for EC2? The GitHub repo is 404 🤷 
- Also some stuff for PloneSoftwareCenter
- A bunch of 'oca-psc-team' packages, but I don't understand what they are

**Comment by pauleveritt** [comment]
Right, in my writeup I started to refer to `psga` for PyScript Gallery. Though I'm up for a better name.

**Comment by tildebyte** [comment]
I'm actually kinda partial to 'psga' 😁
